
INSERT INTO users VALUES (1,'mileycyrus','password');
INSERT INTO users VALUES (2,'taylorswift','password');
INSERT INTO users VALUES (3,'jonbonjovi','password');
INSERT INTO users VALUES (4,'littlewayne','password');
INSERT INTO users VALUES (5,'kimkardashian','password');
INSERT INTO users VALUES (6,'ladygaga','password');
INSERT INTO users VALUES (7,'rickross','password');
INSERT INTO users VALUES (8,'snoopdogg','password');
INSERT INTO users VALUES (9,'aliciakeys','password');
INSERT INTO users VALUES (10,'madonna','password');
INSERT INTO user_rooms VALUES (2,1,2);
INSERT INTO user_rooms VALUES (3,2,1);
INSERT INTO user_rooms VALUES (4,2,2);
INSERT INTO user_rooms VALUES (5,3,1);
INSERT INTO user_rooms VALUES (6,3,9);
INSERT INTO user_rooms VALUES (7,4,1);
INSERT INTO user_rooms VALUES (8,4,9);
INSERT INTO user_rooms VALUES (9,5,1);
INSERT INTO user_rooms VALUES (10,5,2);
INSERT INTO user_rooms VALUES (11,6,1);
INSERT INTO user_rooms VALUES (12,6,2);
INSERT INTO user_rooms VALUES (13,7,1);
INSERT INTO user_rooms VALUES (14,7,9);
INSERT INTO user_rooms VALUES (15,8,1);
INSERT INTO user_rooms VALUES (16,8,9);
INSERT INTO user_rooms VALUES (17,9,1);
INSERT INTO user_rooms VALUES (18,9,2);
INSERT INTO user_rooms VALUES (19,10,1);
INSERT INTO user_rooms VALUES (20,10,2);
INSERT INTO user_rooms VALUES (21,4,3);
INSERT INTO user_rooms VALUES (22,7,3);
INSERT INTO user_rooms VALUES (23,8,3);
INSERT INTO user_rooms VALUES (24,1,4);
INSERT INTO user_rooms VALUES (25,2,4);
INSERT INTO user_rooms VALUES (26,3,4);
INSERT INTO user_rooms VALUES (27,6,4);
INSERT INTO user_rooms VALUES (28,9,4);
INSERT INTO user_rooms VALUES (29,10,4);
INSERT INTO user_rooms VALUES (30,5,5);
INSERT INTO user_rooms VALUES (31,1,7);
INSERT INTO user_rooms VALUES (32,2,7);
INSERT INTO user_rooms VALUES (33,3,7);
INSERT INTO user_rooms VALUES (34,6,7);
INSERT INTO user_rooms VALUES (35,10,7);
INSERT INTO user_rooms VALUES (36,4,8);
INSERT INTO user_rooms VALUES (37,7,8);
INSERT INTO user_rooms VALUES (38,8,8);
INSERT INTO user_rooms VALUES (39,9,8);
INSERT INTO user_rooms VALUES (40,1,6);
INSERT INTO user_rooms VALUES (41,2,6);
INSERT INTO user_rooms VALUES (42,3,6);
INSERT INTO user_rooms VALUES (43,4,6);
INSERT INTO user_rooms VALUES (44,5,6);
INSERT INTO user_rooms VALUES (45,6,6);
INSERT INTO user_rooms VALUES (46,7,6);
INSERT INTO user_rooms VALUES (47,8,6);
INSERT INTO user_rooms VALUES (48,9,6);
INSERT INTO user_rooms VALUES (49,10,6);
INSERT INTO schema_migrations VALUES ('20151015023540');
INSERT INTO schema_migrations VALUES ('20151015024227');
INSERT INTO schema_migrations VALUES ('20151015025001');
INSERT INTO schema_migrations VALUES ('20151015025445');
INSERT INTO schema_migrations VALUES ('20151015025720');
INSERT INTO schema_migrations VALUES ('20151015025735');
INSERT INTO schema_migrations VALUES ('20151015050053');
INSERT INTO schema_migrations VALUES ('20151015070427');
INSERT INTO schema_migrations VALUES ('20151015080849');
INSERT INTO schema_migrations VALUES ('20151015112452');
INSERT INTO schema_migrations VALUES ('20151015112639');
INSERT INTO schema_migrations VALUES ('20151015112651');
INSERT INTO rooms VALUES (1,'Pluto','Everyone is in this chat room');
INSERT INTO rooms VALUES (2,'Saturn','Women are in this chat room');
INSERT INTO rooms VALUES (3,'Mars','Rappers are in this chat room');
INSERT INTO rooms VALUES (4,'Uranus','Pop singers are in this chat room');
INSERT INTO rooms VALUES (5,'Mercury','Reality TV stars are in this chat room');
INSERT INTO rooms VALUES (6,'Earth','Everyone is in this chat room');
INSERT INTO rooms VALUES (7,'Venus','White people are in this chat room');
INSERT INTO rooms VALUES (8,'Jupiter','Black people are in this chat room');
INSERT INTO rooms VALUES (9,'Neptune','Men are in this chat room');
INSERT INTO room_users VALUES (1,2,1);
INSERT INTO room_users VALUES (2,2,2);
INSERT INTO room_users VALUES (3,2,5);
INSERT INTO room_users VALUES (4,2,6);
INSERT INTO room_users VALUES (5,2,9);
INSERT INTO room_users VALUES (6,2,10);
INSERT INTO room_users VALUES (7,9,3);
INSERT INTO room_users VALUES (8,9,4);
INSERT INTO room_users VALUES (9,9,7);
INSERT INTO room_users VALUES (10,9,8);
INSERT INTO room_users VALUES (11,1,1);
INSERT INTO room_users VALUES (12,1,2);
INSERT INTO room_users VALUES (13,1,3);
INSERT INTO room_users VALUES (14,1,4);
INSERT INTO room_users VALUES (15,1,5);
INSERT INTO room_users VALUES (16,1,6);
INSERT INTO room_users VALUES (17,1,7);
INSERT INTO room_users VALUES (18,1,8);
INSERT INTO room_users VALUES (19,1,9);
INSERT INTO room_users VALUES (20,1,10);
INSERT INTO room_users VALUES (21,3,4);
INSERT INTO room_users VALUES (22,3,7);
INSERT INTO room_users VALUES (23,3,8);
INSERT INTO room_users VALUES (24,4,1);
INSERT INTO room_users VALUES (25,4,2);
INSERT INTO room_users VALUES (26,4,3);
INSERT INTO room_users VALUES (27,4,6);
INSERT INTO room_users VALUES (28,4,9);
INSERT INTO room_users VALUES (29,4,10);
INSERT INTO room_users VALUES (30,5,5);
INSERT INTO room_users VALUES (31,7,1);
INSERT INTO room_users VALUES (32,7,2);
INSERT INTO room_users VALUES (33,7,3);
INSERT INTO room_users VALUES (34,7,6);
INSERT INTO room_users VALUES (35,7,10);
INSERT INTO room_users VALUES (36,8,4);
INSERT INTO room_users VALUES (37,8,7);
INSERT INTO room_users VALUES (38,8,8);
INSERT INTO room_users VALUES (39,8,9);
INSERT INTO room_users VALUES (40,6,1);
INSERT INTO room_users VALUES (41,6,2);
INSERT INTO room_users VALUES (42,6,3);
INSERT INTO room_users VALUES (43,6,4);
INSERT INTO room_users VALUES (44,6,5);
INSERT INTO room_users VALUES (45,6,6);
INSERT INTO room_users VALUES (46,6,7);
INSERT INTO room_users VALUES (47,6,8);
INSERT INTO room_users VALUES (48,6,9);
INSERT INTO room_users VALUES (49,6,10);
INSERT INTO profiles VALUES (19,9,'Girl on fire','Alicia Augello Cook (born January 25, 1981), known by the pseudonym Alicia Keys, is an American singer, songwriter, record producer, and actress. Keys released her debut album with J Records, having had previous record deals first with Columbia and then Arista Records. Keys'' debut album, Songs in A Minor, was a commercial success, selling over 12 million copies worldwide. She became the best-selling new artist and best-selling R&B artist of 2001.');
INSERT INTO profiles VALUES (20,4,'Six foot seven foot','Dwayne Michael Carter, Jr., known by his stage name Lil Wayne, is an American rapper from New Orleans, Louisiana. In 1991, at the age of nine, Lil Wayne joined Cash Money Records as the youngest member of the label, and half of the duo The B.G.''z, alongside fellow New Orleans-based rapper Lil'' Doogie. In 1996, Lil Wayne formed the southern hip hop group Hot Boys, with his Cash Money label-mates Juvenile, Young Turk and Lil'' Doogie (who now goes by B.G.). Hot Boys debuted with Get It How U Live!, that same year. Most of the group''s success came with their platinum-selling album Guerrilla Warfare (1999) and the 1999 single "Bling Bling". Along with being the flagship artist of Cash Money Records, Lil Wayne is also the chief executive officer (CEO) of his own label imprint, Young Money Entertainment, which he founded in 2005.');
INSERT INTO profiles VALUES (21,10,'Like a virgin','Madonna Louise Ciccone is an American singer, songwriter, actress, dancer and businesswoman. She achieved popularity by pushing the boundaries of lyrical content in mainstream popular music and imagery in her music videos, which became a fixture on MTV. Madonna is known for reinventing both her music and image, and for maintaining her autonomy within the recording industry. Music critics have acclaimed her musical productions, which have generated some controversy. Often referred to as the "Queen of Pop", she is cited as an influence by numerous other artists around the world.');
INSERT INTO profiles VALUES (22,6,'Bad romance','Stefani Joanne Angelina Germanotta, better known by her stage name Lady Gaga, is an American singer, songwriter, and actress. She is known for her self-empowering messages, fashion, and live performances. Gaga initially performed in theater, appearing in high school plays, and studied at CAP21 through New York University''s Tisch School of the Arts before dropping out to pursue a musical career. After leaving a rock band, participating in the Lower East Side''s avant garde performance art circuit, and being dropped from a contract with Def Jam Recordings, Gaga worked as a songwriter for Sony/ATV Music Publishing. There, recording artist Akon noticed her vocal abilities and helped her to sign a joint deal with Interscope Records and his own KonLive Distribution.');
INSERT INTO profiles VALUES (23,7,'Like a boss','William Leonard Roberts II (born January 28, 1976), better known by his stage name Rick Ross, is an American rapper. In 2009, Ross founded the record label Maybach Music Group, on which he released his studio albums Deeper Than Rap (2009), Teflon Don (2010), God Forgives, I Don''t (2012), Mastermind and Hood Billionaire (2014). Ross was also the first artist signed to Diddy''s management company Ciroc Entertainment. In early 2012, MTV named Ross as the Hottest MC in the Game.');
INSERT INTO profiles VALUES (24,1,'Came in like a wrecking ball','Miley Ray Cyrus is an American singer, songwriter, and actress. Born and raised in Franklin, Tennessee, she held minor roles in the television series Doc and the film Big Fish in her childhood. Cyrus became a teen idol for her portrayal of the starring character Miley Stewart in the Disney Channel television series Hannah Montana in 2006; her father Billy Ray Cyrus additionally starred in the show. Cyrus subsequently signed a recording contract with Hollywood Records; her debut studio album Meet Miley Cyrus (2007) was certified quadruple-platinum by the Recording Industry Association of America (RIAA) for exceeding four million shipments. Cyrus released her second album Breakout and launched her film career as a voice actress in the animated film Bolt in 2008.');
INSERT INTO profiles VALUES (25,3,'Living on a prayer','Bon Jovi is an American rock band from Sayreville, New Jersey. Formed in 1983, Bon Jovi consists of lead singer and namesake Jon Bon Jovi (born John Francis Bongiovi, Jr.), pianist and keyboard player David Bryan, and drummer Tico Torres. The band''s lineup has remained mostly static during its history, with the only exceptions being the 1994 dismissal of bass player Alec John Such, who was unofficially replaced by Hugh McDonald, and the departure of longtime guitarist and co-songwriter Richie Sambora in 2013. In 1986, Bon Jovi achieved widespread global recognition with their third album, Slippery When Wet.');
INSERT INTO profiles VALUES (26,8,'Fo shizzle','Calvin Cordozar Broadus, Jr. best known by his stage name Snoop Dogg, is an American rapper and actor from Long Beach, California. His music career began in 1992, when he was discovered by Dr. Dre of N.W.A and as a result was prominently featured throughout Dr. Dre''s solo debut album, The Chronic (1992). He has since sold over 21 million albums in United States and 35 million albums worldwide.');
INSERT INTO profiles VALUES (27,2,'Never gettng back together','Taylor Alison Swift is an American singer-songwriter and actress. Raised in Wyomissing, Pennsylvania, she moved to Nashville, Tennessee, at the age of 14 to pursue a career in country music. She signed with the independent label Big Machine Records and became the youngest songwriter ever hired by the Sony/ATV Music publishing house. The release of Swift''s self-titled debut album in 2006 marked the start of her career as a country music singer. Her third single, "Our Song," made her the youngest person to single-handedly write and perform a number-one song on the Hot Country Songs chart.');
INSERT INTO profiles VALUES (28,5,'Reality TV sensation','Kimberly "Kim" Kardashian West is an American television and social media personality, actress, socialite, and model. Born and raised in Los Angeles, California, Kardashian first gained media attention through her friendship with Paris Hilton, but she received wider notice after a 2003 sex tape with her former boyfriend Ray J was leaked in 2007. Later that year, she and her family began to appear in the reality television series Keeping Up with the Kardashians. Its success has led to the creation of spin-offs including Kourtney and Kim Take New York and Kourtney and Kim Take Miami. In 2010, Kardashian was reported to be the highest-paid reality television personality, with estimated earnings of US$6 million.');
INSERT INTO posts VALUES (1,1,6,'I am the best singer.');
INSERT INTO posts VALUES (2,2,6,'I love lamp.');
INSERT INTO posts VALUES (3,3,6,'I sing good.');
INSERT INTO posts VALUES (4,4,6,'I am so cool.');
INSERT INTO posts VALUES (5,5,6,'I am famous.');
INSERT INTO posts VALUES (6,6,6,'I have tons of money.');
INSERT INTO posts VALUES (7,7,6,'I see dead people.');
INSERT INTO posts VALUES (8,8,6,'I want to go home.');
INSERT INTO posts VALUES (9,9,6,'I love this chat room.');
INSERT INTO posts VALUES (10,10,6,'I don''t want to grow up.');
INSERT INTO posts VALUES (11,5,1,'I''m so bored.');
INSERT INTO posts VALUES (12,5,2,'I''m so bored.');
INSERT INTO posts VALUES (13,5,3,'I''m so bored.');
INSERT INTO posts VALUES (14,5,4,'I''m so bored.');
INSERT INTO posts VALUES (15,5,5,'I''m so bored.');
INSERT INTO posts VALUES (16,5,6,'I''m so bored.');
INSERT INTO posts VALUES (17,5,7,'I''m so bored.');
INSERT INTO posts VALUES (18,5,8,'I''m so bored.');
INSERT INTO posts VALUES (19,5,9,'I''m so bored.');
INSERT INTO posts VALUES (20,1,1,'la la la la la.');
INSERT INTO posts VALUES (21,2,1,'la la la la la.');
INSERT INTO posts VALUES (22,3,1,'la la la la la.');
INSERT INTO posts VALUES (23,4,1,'la la la la la.');
INSERT INTO posts VALUES (24,5,1,'la la la la la.');
INSERT INTO posts VALUES (25,6,1,'la la la la la.');
INSERT INTO posts VALUES (26,7,1,'la la la la la.');
INSERT INTO posts VALUES (27,8,1,'la la la la la.');
INSERT INTO posts VALUES (28,9,1,'la la la la la.');
INSERT INTO posts VALUES (29,10,1,'la la la la la.');
